### ISSUE TITLE
Lab 3 Review by Sofer Fabio

### ISSUE THREAD

**Issue by FabioSofer** [saccuz/Computational_Intelligence#5]
## Code Structure
The readmes are very in-depth and make code analysis much easier, the code itself is scarcely commented, but the readmes divided by tasks make it easy to keep track of what are the ideas behind the code.

## Tasks 1-2
- I don't see why `cooked['dumb_strategy']` needs to be inside of the cooked status instead of being a normal agent.
- Otherwise, it is good to see multi-rule agents performing well

## Task 3
- It is refreshing to see that you only kept the pieces that you needed of your nim.py file and modified them instead of copying the whole file.
- Your performance is very strong (fast execution times up to very large nim sizes), but I am not sure how exactly how much making random moves is penalizing the winrate of your Agent, against an optimal opponent making one mistake should lose you the match, but the readme would suggest otherwise, a graph of the winrates since you are already tracking execution time could be a welcome addition.

## Task 4
Clean implementation of the outline given to us by the assistant Professor.

**Comment by saccuz** [comment]
Task 1-2: You are right about dumb strategy. It is part of the professor's code that was never truly reworked before task 3.
Task 3: the winrate is fine against non optimal strategy. Against nim-sum in a Nim of dimension > 10 (as I remember) the minmax loses. But given the incredibly high space of the solution, it was unfeasible to proceed with further explorations.
